name: Build Distribution
on: [pull_request]
jobs:
  build-distribution:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=8092"

    steps:
    - uses: actions/checkout@v2
    - name: Build node js module
      uses: gps/ncc-gha@master
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
